#%RAML 1.0
title: ModelConstructor API
version: v1.0
baseUri: https://api.seb.com/{version}/model
mediaType:  application/json
types:
  Data:
    type: object
    properties:
      Headers: FieldInfo[]
      Rows: Row[]
  FieldInfo:
    type: object
    properties:
      name: string
      type:  string
  Row:
    type: object
    properties:
      fields: Field[]
  Field:
    type: object
    properties:
      numeric: number
      categorial: string
      date: Date
      
  Date:
    type: string
    pattern: "\\d\\d-\\d\\d-\\d\\d\\d\\d"
/model/create:
  put:
    responses:
      200:
        body:
          application/json:
            type: Data
